In [ ]:
#creating simple 2d array in list

In [2]:
import numpy as np
arr =np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [3]:
arr.ndim

3

In [4]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [5]:
arr.strides

(8, 4)

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr1=np.arange(12).reshape(2,6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [12]:
bools=[False,True,False,True,False]
b=np.array(bools)
print(b.sum())
print(b.any())
print(b.all())

2
True
False
