In [1]:
import cv2

In [2]:
img=cv2.imread("cat-2083492__340.jpg")


In [3]:
b,g,r=cv2.split(img)
img=cv2.merge((b,g,r))

In [4]:
img[0]

array([[  0,  46,  28],
       [ 20,  65,  48],
       [ 19,  55,  43],
       ...,
       [ 53, 163, 159],
       [ 54, 164, 160],
       [ 53, 163, 159]], dtype=uint8)

In [5]:
img[0][0]=[0,0,0]
b=b-r
r=r-g
g=g-g
print(b)
print(r)
print(g)

[[228 228 232 ... 150 150 150]
 [242 247 243 ... 150 150 150]
 [234 235 233 ... 150 150 150]
 ...
 [228 220 207 ... 177 177 181]
 [237 220 207 ... 177 177 181]
 [236 220 207 ... 177 177 181]]
[[238 239 244 ... 252 252 252]
 [239 241 244 ... 252 252 252]
 [242 242 245 ... 252 252 252]
 ...
 [231 232 240 ... 246 246 243]
 [231 232 240 ... 246 246 243]
 [231 232 240 ... 246 246 243]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [6]:
img=cv2.merge((b,g,r))

In [7]:
for i in range(340):
    img[0][i]=[0,0,0]    

In [8]:
cv2.imshow('cat',img)
cv2.waitKey()
cv2.destroyAllWindows() 

In [ ]:
import numpy as np
kernal1=np.array([[0,0,0],
                 [0,1,0],
                 [0,0,1]])
identity=cv2.filter2D(src=img,ddepth=-1,kernel=kernal1)
cv2.imshow('Original',img)
cv2.imshow('Identity',identity)
cv2.waitKey()
cv2.imwrite('identity.jpg',identity)
cv2.destroyAllWindows()